# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint-plugin-storybook"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"
      testing-library:
        patterns:
          - "@testing-library/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-plugin-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "@eslint/*"
          - "typescript-eslint"
      types:
        patterns:
          - "@types/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "tailwindcss-*"
          - "@tailwindcss/*"
          - "autoprefixer"
          - "postcss"
      react:
        patterns:
          - "react"
          - "react-*"
